# Generated by Django 4.1.1 on 2022-12-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='usr/%y')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
