# Generated by Django 4.1.1 on 2022-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_images_delete_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
